- name: Add GitLab repository
  shell: |
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

- name: Install GitLab
  apt:
    name: gitlab-ce
    state: present

- name: Configure GitLab
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url'
    line: "external_url 'http://{{ inventory_hostname }}'"
- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure

